import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { App, View } from "@/lib/framework7";

// Import Framework7 Styles
import "framework7/css/bundle";
import "@/lib/framework7";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import routes from "@/lib/routes";
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();

  const path = headersList.get("x-pathname");

  /*
    Here we need to know (mostly on server-side) on what URL user opens our app
  */
  const url = `${process.env.NEXT_PUBLIC_HOST}${path}`;

  return (
    <html lang="en">
      <body className={inter.className}>
        <App url={url} routes={routes}>
          {/*
        Create main View.
        Apparently we need to enable browserHistory to navigating by URL
      */}
          <View
            main
            // browserHistory
            // browserHistorySeparator=""
            // browserHistoryInitialMatch={true}
            // browserHistoryStoreHistory={false}
            // browserHistoryAnimate={false}
            url="/"
          >
            {children}
          </View>
        </App>
      </body>
    </html>
  );
}
